#########################################################################################################################################################
#########################################################################################################################################################
############################################################## Sem Sugestao #############################################################################
#########################################################################################################################################################
#########################################################################################################################################################
#########################################################################################################################################################
#########################################################################################################################################################

# Filtro 1: marcaCAo de VerbalizaCAo ou nAo de insatisfaCAo

#Filtro do B2C:
dados$SemSugestao<-ifelse(
   stringdist(dados$texto,'SEM SUGESTAO')<=2
  |stringdist(dados$texto,'NAO, NAO TENHO NENHUMA.')<=4
  |stringdist(dados$texto,'N')<=1
  |stringdist(dados$texto,'X')<=1
  |stringdist(dados$texto,'/')<=1
  |stringdist(dados$texto,'NA')<=1
  |stringdist(dados$texto,'OK')<=1
  |stringdist(dados$texto,'ND')<=1
  |stringdist(dados$texto,'NAO//')<=1
  |stringdist(dados$texto,'NNAO/')<=1
  |stringdist(dados$texto,'NADA/')<=1
  |stringdist(dados$texto,'NAQO/')<=1
  |stringdist(dados$texto,'NOAO/')<=1
  |stringdist(dados$texto,'NENHUM')<=2
  |stringdist(dados$texto,'NAO/SO')<=2
  |stringdist(dados$texto,'SEM OBS/')<=2
  |stringdist(dados$texto,'NAO NADA')<=2
  |stringdist(dados$texto,'NAO OPINA')<=3
  |stringdist(dados$texto,'AGORA NAO')<=2
  |stringdist(dados$texto,'NH/')<=1
  |stringdist(dados$texto,'N AO')<=1
  |stringdist(dados$texto,'TEST')<=1
  |stringdist(dados$texto,'NAO_/')<=2
  |stringdist(dados$texto,'GERAL/')<=2
  |stringdist(dados$texto,'NANAO/')<=2
  |stringdist(dados$texto,'SEI NAO')<=2
  |stringdist(dados$texto,'NAO NAO')<=2
  |stringdist(dados$texto,'SEM OBS')<=3
  |stringdist(dados$texto,'NEGATIVO/')<=2
  |stringdist(dados$texto,'HOJE NAO/')<=3
  |stringdist(dados$texto,'EU NAO SEI')<=2
  |stringdist(dados$texto,'NAO DESEJA')<=2
  |stringdist(dados$texto,'NAOP OPANI')<=3
  |stringdist(dados$texto,'NADA ADIZER')<=3
  |stringdist(dados$texto,'NAO,NAO./SO.')<=3
  |stringdist(dados$texto,'NAO/OBRIGADA')<=2
  |stringdist(dados$texto,'NAO LEMBRA /')<=2
  |stringdist(dados$texto,'SUGESTAO NAO')<=2
  |stringdist(dados$texto,'NADA EM MENTE')<=2
  |stringdist(dados$texto,'A PRIORI NAO/')<=2
  |stringdist(dados$texto,'A PRINCIPIO NAO')<=2
  |stringdist(dados$texto,'NAO QUER FALAR/')<=3
  |stringdist(dados$texto,'NO MOMENTO NAO/')<=3
  |stringdist(dados$texto,'NAO QUER FALAR/')<=3
  |stringdist(dados$texto,'NAO. NAO DESEJO')<=3
  |stringdist(dados$texto,'NADA A DECLARAR')<=3
  |stringdist(dados$texto,'SEM PROBLEMAS /')<=2
  |stringdist(dados$texto,'POR ENQUANTO NAO')<=2
  |stringdist(dados$texto,'NAO ESTA TD BEM/')<=2
  |stringdist(dados$texto,'NAO TA TRANQUILO')<=2
  |stringdist(dados$texto,'SEM COMENTARIOS//')<=2
  |stringdist(dados$texto,'NAO QUIS INFORMAR')<=4
  |stringdist(dados$texto,'NESTE MOMENTO NAO')<=3
  |stringdist(dados$texto,'A PRIORE NAO./SO.')<=3
  |stringdist(dados$texto,'EU CREIO QUE NAO/')<=3
  
  |stringdist(dados$texto,'NO MOMENTO EU NAO TENHO NENHUMA OPNIAO')<=6
  |stringdist(dados$texto,'DE REPENTE NÃO TENHO NADA PARA SUGERIR')<=6
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO ATUALMENTE.')<=6
  |stringdist(dados$texto,'NAO,NOO SUGESTAO POR ENQUANTO NAO./SO.')<=6
  |stringdist(dados$texto,'NAO, DE IMEDIATO NAO TERIA O QUE DIZER')<=6
  |stringdist(dados$texto,'NAO .NAO QUE EU TENHA NADA EM MENTE /')<=6
  |stringdist(dados$texto,'NAO NESSE MOMENTO NAO. ESTA TRANQUILO')<=6
  |stringdist(dados$texto,'PREFIRO NAO COLOCAR NENHUMA SUGESTAO/')<=6
  |stringdist(dados$texto,'NAO NESSE MOMENTO NAO ME OCORRE NADA/')<=6
  |stringdist(dados$texto,'NAO TENHO NADA AQUI PARA SUGERIR./SO.')<=6
  |stringdist(dados$texto,'COM A FIXA NAO TENHO NENHUM CONSELHO.')<=6
  |stringdist(dados$texto,'NO MOMENTO NAO TENHO NADA A INFORMAR')<=6
  |stringdist(dados$texto,'QUE EU ME LEMBRE DE CABECA AGORA NAO')<=6
  |stringdist(dados$texto,'NAO TENHO INFORMACAO PRA ISSO AINDA/')<=6
  |stringdist(dados$texto,'NAO. NAO TENHO NENHUMA SUGESTAO NAO.')<=6
  |stringdist(dados$texto,'NAO. NO MOMENTO ESTA ME ATENDENDO //')<=6
  |stringdist(dados$texto,'NAO PRECISA NAO, NAO HA NECESSIDADE.')<=6
  
  
  
  
  
  |stringdist(dados$texto,'SEM SU')<=3
  |stringdist(dados$texto,'AGORA NAO.')<=3
  |stringdist(dados$texto,'NAO DESEJA.')<=3 
  |stringdist(dados$texto,'NAO TRANQUILO')<=3 
  |stringdist(dados$texto,'NAO, TUDO OK.')<=3 
  |stringdist(dados$texto,'NAO SATISFEITA')<=0 
  |stringdist(dados$texto,'NAO, TA BACANA.')<=3
  |stringdist(dados$texto,'DE MOMENTO NAO.')<=0
  |stringdist(dados$texto,'NAO, TA TUDO BEM')<=3
  |stringdist(dados$texto,'NAO. NAO DESEJO.')<=3
  |stringdist(dados$texto,'NAO SEI TE DIZER.')<=0
  |stringdist(dados$texto,'NO MOMENTO NAO ME RECORDO')<=3                             
  |stringdist(dados$texto,'RECUSA')<=2
  |stringdist(dados$texto,'NAO NAO.')<=2
  |stringdist(dados$texto,'NAO TEM/')<=2
  |stringdist(dados$texto,'NAO TENHO')<=2
  |stringdist(dados$texto,'SEM SEGUSTAO.')<=4
  |stringdist(dados$texto,'NAO, ACHO QUE PRA MIM PERFEITO')<=4
  |stringdist(dados$texto,'NAO . . .')<=2
  |stringdist(dados$texto,'HUM, NAO.')<=2
  |stringdist(dados$texto,'NAO TA BOA')<=2
  |stringdist(dados$texto,'NAO LEMBRO')<=2
  |stringdist(dados$texto,'NAO POSSO.')<=2
  |stringdist(dados$texto,'NAO TO AFIM')<=2
  |stringdist(dados$texto,'SEM MOTIVO.')<=1
  |stringdist(dados$texto,'NAO PRECISA')<=1
  |stringdist(dados$texto,'NAO POR HORA')<=2 
  |stringdist(dados$texto,'NAO OBRIGADA')<=1 
  |stringdist(dados$texto,'NAO TEM NADA')<=2
  |stringdist(dados$texto,'SUGESTAO NAO')<=2
  |stringdist(dados$texto,'SEM RESPOSTA')<=2
  |stringdist(dados$texto,'NAO GOSTARIA')<=2
  |stringdist(dados$texto,'NENHUM MESMO')<=2
  |stringdist(dados$texto,'NAO ATE AGORA')<=2
  |stringdist(dados$texto,'NAO ME LEMBRO')<=2
  |stringdist(dados$texto,'EU NAO QUERO.')<=2
  |stringdist(dados$texto,'NAO, GOSTARIA')<=2
  |stringdist(dados$texto,'AGORA NAO SEI')<=3
  |stringdist(dados$texto,'NAO TERIA NAO')<=3
  |stringdist(dados$texto,'YGYTYU')<=3
  |stringdist(dados$texto,'......')<=1
  |stringdist(dados$texto,'NAO DESEJO SUGERIR')<=3
  |stringdist(dados$texto,'TA BOM, TA BOMNAO.')<=3
  |stringdist(dados$texto,'NO MOMENTO NENHUMA')<=3  
  |stringdist(dados$texto,'NAO TEMM SUGESTOES')<=3  
  |stringdist(dados$texto,'AH NAO, NAONAO SO.')<=3 
  |stringdist(dados$texto,'NAO NAO tenho NAO')<=4 
  
  
  
  |stringdist(dados$texto,'NADA A DECLARAR')<=3
  |stringdist(dados$texto,'POR ENQUANTO NAO.')<=3
  |stringdist(dados$texto,'NAO EM O QUE MELHORAR')<=4
  |stringdist(dados$texto,'NAO POR ENQUANTO NAO.')<=4
  |stringdist(dados$texto,'NAO LEMBRO DE NADA NAO')<=4
  |stringdist(dados$texto,'NAO QUERO FAZER SUGESTAO')<=4
  |stringdist(dados$texto,'SEM SUGESTAO - ESTA BOM ASSIM')<=4
  |stringdist(dados$texto,'NAO TUDO TRANQUILO CONTINUANDO ASSIM')<=4
  |stringdist(dados$texto,'NO MOMENTO NAO TENHO NADA NA CABECA.')<=4
  |stringdist(dados$texto,'NADA A DIZER')<=4
  |stringdist(dados$texto,'A PRINCIPIO NAO')<=4
  |stringdist(dados$texto,'NAO OBRIGADO./SO.')<=4
  |stringdist(dados$texto,'POR ENQUANTO NAO.')<=4
  |stringdist(dados$texto,'NENHUMA SURGESTAO')<=4
  |stringdist(dados$texto,'NAO TENHO SUGESTAO')<=4
  |stringdist(dados$texto,'NAO TENHO SUGESTAO NAO.')<=4
  |stringdist(dados$texto,'NAO SEM SUGESTAO')<=4
  |stringdist(dados$texto,'NAO SEI A SUGESTAO/')<=4
  |stringdist(dados$texto,'NAO DESEJA REALIZAR  SUGESTAO')<=4
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO')<=4
  |stringdist(dados$texto,'NAO SEI')<=4
  |stringdist(dados$texto,'EU NAO SEI')<=4
  |stringdist(dados$texto,'NAO')<=5
  |stringdist(dados$texto,'NAO.SO')<=4
  |stringdist(dados$texto,'NAO,NAO./SO.')<=4
  |stringdist(dados$texto,'NO MOMENTO NAO.')<=4
  |stringdist(dados$texto,'NAO NO MOMENTO')<=4
  |stringdist(dados$texto,'NO MOMENTO')<=4                     
  |stringdist(dados$texto,'NO MOMENTO NAO./SO.')<=4                     
  |stringdist(dados$texto,'NAO NO MOMENTO NAO')<=4                     
  |stringdist(dados$texto,'NAO NO MOMENTO NAO./SO.')<=4                     
  |stringdist(dados$texto,'AGORA NO MOMENTO NAO./SO.')<=4                     
  |stringdist(dados$texto,'NAO,NAO NO MOMENTO NAO./SO.')<=4                     
  |stringdist(dados$texto,'NAO, NAO TENHO')<=3                     
  |stringdist(dados$texto,'NAO NAO')<=3                     
  |stringdist(dados$texto,'NAO TENHO.')<=3                     
  |stringdist(dados$texto,'NAO TENHO NAO./SO.')<=3                     
  |stringdist(dados$texto,'NENHUMA')<=5                     
  |stringdist(dados$texto,'NAO NENHUMA')<=4                     
  |stringdist(dados$texto,'NAO NENHUMA./SO.')<=4																			                     						 
  |stringdist(dados$texto,'TEST'																		                                       )<=4
  |stringdist(dados$texto,'NADA ADIZER'																	                                   )<=4
  |stringdist(dados$texto,'NAO TUDO OK'																            	                       )<=4
  |stringdist(dados$texto,'ACHO QUE NAO'																                                   )<=4
  |stringdist(dados$texto,'NAO QUER FALAR/'																                                 )<=4
  |stringdist(dados$texto,'NAO, ESTA OTIMO.'															                                 )<=4
  |stringdist(dados$texto,'NAO E OTIMO.'																                                   )<=4
  |stringdist(dados$texto,'TA EXCELENTE'																                                   )<=4
  |stringdist(dados$texto,'NADA EM MENTE'																                                   )<=4
  |stringdist(dados$texto,'NA VERDADE NAO'															                                   )<=4
  |stringdist(dados$texto,'A PRIORE NAO./SO.'															                                 )<=4
  |stringdist(dados$texto,'VOLTAR A SER GVT.'															                                 )<=4
  |stringdist(dados$texto,'NAO ESTA TUDO OTIMO'															                               )<=4
  |stringdist(dados$texto,'NAO, ESTA TRANQUILO'															                               )<=4
  |stringdist(dados$texto,'NAO ESTOU SATISFEITA'														                               )<=4
  |stringdist(dados$texto,'NAO TENHO QUEIXA NAO'														                               )<=4
  |stringdist(dados$texto,'NAO TENHO RECLAMACAO'														                               )<=4
  |stringdist(dados$texto,'NAO. TUDO TRANQUILO.'														                               )<=4
  |stringdist(dados$texto,'NAO POR HORA NAO./SO.'														                               )<=4
  |stringdist(dados$texto,'PRA MIM ESTA PERFEITO.'														                             )<=4
  |stringdist(dados$texto,'NAO MUITO OBRIGADO./SO.'														                             )<=4
  |stringdist(dados$texto,'NAO NADA EM MENTE AGORA'														                             )<=4
  |stringdist(dados$texto,'NAO QUERO COMENTAR NADA'														                             )<=4
  |stringdist(dados$texto,'NAO SEMPRE FOI ATENDIDA'														                             )<=4
  |stringdist(dados$texto,'NAO, ESTA TUDO CERTINHO'														                             )<=4
  |stringdist(dados$texto,'A TELEFONIA FIXA E BOA//'													                             )<=4
  |stringdist(dados$texto,'NAO / ESTA TUDO OTIMO //'													                             )<=4
  |stringdist(dados$texto,'NAO SEI NAO PENSEI NISSO'				                         	                     )<=4
  |stringdist(dados$texto,'NAO TENHO NADA EM MENTE.'				                         	                     )<=4
  |stringdist(dados$texto,'NAO, POR HORA TA TUDO OK'				                         	                     )<=4
  |stringdist(dados$texto,'NO MOMENTO NAO SEI DIZER'				                         	                     )<=4
  |stringdist(dados$texto,'NAO PARA MIM ESTA TUDO OK'				                         	                     )<=4
  |stringdist(dados$texto,'NO MOMNETO NADA EM MENTE.'			                                                 )<=4
  |stringdist(dados$texto,'NAO TENHO NADA A RECLAMAR.'		                                                 )<=4
  |stringdist(dados$texto,'NAO ATUALMENTE AQUI TA BOM.'		                                                 )<=4
  |stringdist(dados$texto,'NAO TENHO RESPOSTA PARA DAR'		                                                 )<=4
  |stringdist(dados$texto,'NAO, ESTA TUDO TRANQUILO //'		                                                 )<=4
  |stringdist(dados$texto,'DA MAIS ATENCAO AO CLIENTE /'	                                                 )<=4
  |stringdist(dados$texto,'NAO PRA MIM ESTA TUDO OTIMO.'	                                                 )<=4
  |stringdist(dados$texto,'NAO TENHO SUGESTAO NENHUMA//'	                                                 )<=4
  |stringdist(dados$texto,'NAO, APENAR ABAIXAR O PRECO.'	                                                 )<=4
  |stringdist(dados$texto,'NO MOMENTO NAO TENHO NENHUM/'	                                                 )<=4
  |stringdist(dados$texto,'DEIXA PRA LA / NAO QUIZ FALAR'	                                                 )<=4
  |stringdist(dados$texto,'NAO POR ENQUANTO NAO TEM NADA'                                                  )<=4
  |stringdist(dados$texto,'NAO QUERO ENTRAR EM DETALHES.'	                                                 )<=4
  |stringdist(dados$texto,'NAO SABERIA FALAR NO MOMENTO.'	                                                 )<=4
  |stringdist(dados$texto,'NAO TENHO NADA A ACRESSCENTAR'	                                                 )<=4
  |stringdist(dados$texto,'NAO TENHO OPINIAR A RESPEITO.'                                                  )<=4
  |stringdist(dados$texto,'NAO, ACHO QUE NO MOMENTO NAO.'                                                  )<=4
  |stringdist(dados$texto,'NAO, PARA MIM ESTA MUITO BOM.'                                                  )<=4
  |stringdist(dados$texto,'NAO TENHO NADA EM PENSAMENTO /'	                                               )<=4
  |stringdist(dados$texto,'HOJE NAO TENHO NENHUMA SUGESTAO'	                                               )<=4
  |stringdist(dados$texto,'AGORA NAO TENHO NENHUMA SUGESTAO'                                               )<=4
  |stringdist(dados$texto,'NAO ACHO COMPLETO, ACHO PERFEITO'                                               )<=4
  |stringdist(dados$texto,'NAO NO MOMENTO ESTOU SATISFEITA.'                                               )<=4
  |stringdist(dados$texto,'NAO PRA MIM ESTA BOM, ESTA OTIMA'                                               )<=4
  |stringdist(dados$texto,'NAO,NAO POR ENQUANTO NENHUM./SO.'											                         )<=4
  |stringdist(dados$texto,'NAO,NAO,NAO,NAO PRECISA NAO./SO.'											                         )<=4
  |stringdist(dados$texto,'CONTINUANDO COMO ESTA JA ESTA BOM'											                         )<=4
  |stringdist(dados$texto,'DE CABECA NO MOMENTO NAO VEM NADA'											                         )<=4
  |stringdist(dados$texto,'NAO.  NAO TENHO NENHUMA SUGESTAO.'											                         )<=4
  |stringdist(dados$texto,'NAO. ESTA TUDO BEM GRACAS A DEUS.'											                         )<=4
  |stringdist(dados$texto,'NAO, NAO TENHO MUITO RECLAMAR NAO.'											                       )<=4
  |stringdist(dados$texto,'NAO,NAO,NAO PARA MIM ESTA BOM./SO.'											                       )<=4
  |stringdist(dados$texto,'QUE CONTINUE BEM DO JEITO QUE ESTA'											                       )<=4
  |stringdist(dados$texto,'NAO DESEJO RELIAZAR NENHUM SUGESTAO'											                       )<=4
  |stringdist(dados$texto,'NAO ESTA SENDO BOM PORQUE ESTA CARO'											                       )<=4
  |stringdist(dados$texto,'NAO SI / SO OS SERVIOS NAO SAO BONS'											                       )<=4
  |stringdist(dados$texto,'NAO, ACHO QUE ESTA TUDO NOTA 10./SO'											                       )<=4
  |stringdist(dados$texto,'NAO,NAO TENHO NENHUMA SUGESTAO./SO.'											                       )<=4
  |stringdist(dados$texto,'NAO,NAO,NAO NAO QUERO OBRIGADA./SO.'											                       )<=4
  |stringdist(dados$texto,'NO MOMENTO NAO ESTOU LEMBRANDO NADA'											                       )<=4
  |stringdist(dados$texto,'NAO DESEJO REALIZAR NENHUMA SUGESTAO'										                       )<=4
  |stringdist(dados$texto,'NAO NENHUMA PARA MIM ESTA OTIMA./SO.'										                       )<=4
  |stringdist(dados$texto,'NAO. NO MOMENTO ESTA ME ATENDENDO //'										                       )<=4
  |stringdist(dados$texto,'COM A FIXA NAO TENHO NENHUM CONSELHO.'										                       )<=4
  |stringdist(dados$texto,'NAO TENHO NADA AQUI PARA SUGERIR./SO.'										                       )<=4
  |stringdist(dados$texto,'DE REPENTE NAO TENHO NADA PARA SUGERIR'										                     )<=4
  |stringdist(dados$texto,'NAO ACHO QUE NAO POR ENQUANTO NAO./SO.'										                     )<=4
  |stringdist(dados$texto,'NAO SEI O QUE FALAR / NAO SEI EXPLICAR'										                     )<=4
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO ATUALMENTE.'										                     )<=4
  |stringdist(dados$texto,'NAO TRANQUILO ESTA DE BOM TAMANHO./SO.'										                     )<=4
  |stringdist(dados$texto,'NAO, CONCERVANDO JA E UM GRANDE PASSO.'										                     )<=4
  |stringdist(dados$texto,'NA. EU TERIA QUE ESTAR OBSERVANDO MAIS.'										                     )<=4
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO POR ENQUANTO'										                     )<=4
  |stringdist(dados$texto,'POR ENQUANTO NAO TENHO NENHUMA SUGESTAO'										                     )<=4
  |stringdist(dados$texto,'DE MOMENTO NAO, NAO TENHO NENHUMA IDEIA.'									                     )<=4
  |stringdist(dados$texto,'NAO DESEJA REALIZAR SUGESTAO DE MELHORIA'									                     )<=4
  |stringdist(dados$texto,'NO MOMENTO, NAO DESEJA REALIZAR SUGESTAO'									                     )<=4
  |stringdist(dados$texto,'NAO NO MOMENTO NAO VEM NADA A CABECA./SO.'									                     )<=4
  |stringdist(dados$texto,'NAO, NO MOMENTO ESTA ME ATENDENDO TUDO OK'									                     )<=4
  |stringdist(dados$texto,'NAO, O QUE EU TENHO USADO TEM ME ATENDIDO.'									                   )<=4
  |stringdist(dados$texto,'NA PARTE DO FIXO NAO TENHO NENHUMA SUGESTAO'									                   )<=4
  |stringdist(dados$texto,'NAO, ATE AGORA A GENTE ESTA BEM SATISFEITO.'									                   )<=4
  |stringdist(dados$texto,'POR QUE ESTA RECENTE E NAO TEM COMO DAR DEZ.'								                   )<=4
  |stringdist(dados$texto,'HA NO MOMENTO EU NAO TENHO NADA PENDENTE./SO.'								                   )<=4
  |stringdist(dados$texto,'NAO EU USO MUITO POUCO E ELES ME ATENDEM BEM.'								                   )<=4
  |stringdist(dados$texto,'NAO NAO TYENHO OQUE RECLAMAR PRA MIM E OTIMO.'								                   )<=4
  |stringdist(dados$texto,'NAO, PORQUE ESTOU CONTENTE, ESTOU SATISFEITO.'								                   )<=4
  |stringdist(dados$texto,'NAO. NO MOMENTO NAO CONSIGO PENSAR EM NADA //'								                   )<=4
  |stringdist(dados$texto,'NADA EM MENTE AQUI AGORA NENHUMA SUGESTAO./SO.'								                 )<=4
  |stringdist(dados$texto,'PRA FALAR A VERDADE, NAO. ESTOU BEM SATISFEITA'								                 )<=4
  |stringdist(dados$texto,'NAO DESEJO REALIZAR NENHUMA SUGESTAO NO MOMENTO'								                 )<=4
  |stringdist(dados$texto,'NAO PARA MIM O SERVICO QUE ESTA TENDO JA E  BOM'								                 )<=4
  |stringdist(dados$texto,'NO MOMENTO NAO TENHO COMO SUGERIR ALGUMA COISA.'								                 )<=4
  |stringdist(dados$texto,'NAO MOMENTO NAO DESEJO REALIZAR NENHUMA SUGESTAO'							                 )<=4
  |stringdist(dados$texto,'NO MOMENTO NAO, ULTIMAMENTE NAO TEVE MAIS PROBLEMAS.'						               )<=4
  |stringdist(dados$texto,'NAO, ESTA TUDO TRANQUILLO, ESTOU SENDO BEM ATENDIDO.'						               )<=4
  |stringdist(dados$texto,'NAO. FUI BEM ATENDIDA EM TODOS OS MOMENTOS QUE LIGUEI'						               )<=4
  |stringdist(dados$texto,'PRA MIM PELO OQUE EU JA PASSEI O DA NET ESTA TUDO OK.'						               )<=4
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO PORQUE E MUITO COMPLEXO ISSO.'					             )<=4
  |stringdist(dados$texto,'NAO PARA MIM O QUE A VIVO OFERECE ESTA PERFEITO NAO TENHO NADA A ACRESCENTAR'   )<=4
  |stringdist(dados$texto,'NAO TENHO NENHUMA SUGESTAO, DENTRO DO QUE EU SOLICITEI ESTA TUDO OTIMO PARA MIM')<=4
  |stringdist(dados$texto,'NAO..')<=1
  |stringdist(dados$texto,'NAO/ CONTINUAR DO JEITO QUE TA')<=2
  |stringdist(dados$texto,'NESSE MOMENTO NAO.')<=2
  |stringdist(dados$texto,'AGORA NO MOMENTO NAO.')<=2
  |stringdist(dados$texto,'NAO, PRA MIM ESTA OTIMO.')<=2
  |stringdist(dados$texto,'NAO, NAO, PRA MIM TA BOM.')<=2
  |stringdist(dados$texto,'NAO TENHO NAO.')<=2
  |stringdist(dados$texto,'NAO////')<=2
  |stringdist(dados$texto,'NENHUM.')<=2
  |stringdist(dados$texto,'HOJE NAO.')<=2
  |stringdist(dados$texto,'POR ENQUANTO NAO.')<=2
  |stringdist(dados$texto,'NAO, AGORA NAO.')<=2
  |stringdist(dados$texto,'SEM SU')<=3
  |stringdist(dados$texto,'AGORA NAO.')<=3
  |stringdist(dados$texto,'NAO DESEJA.')<=3 
  |stringdist(dados$texto,'NAO TRANQUILO')<=3 
  |stringdist(dados$texto,'NAO, TUDO OK.')<=3 
  |stringdist(dados$texto,'NAO SATISFEITA')<=0 
  |stringdist(dados$texto,'NAO, NAO TENHO')<=3
  |stringdist(dados$texto,'NAO, TA BACANA.')<=3
  |stringdist(dados$texto,'DE MOMENTO NAO.')<=0
  |stringdist(dados$texto,'NAO, TA TUDO BEM')<=3
  |stringdist(dados$texto,'NAO. NAO DESEJO.')<=3
  |stringdist(dados$texto,'NAO SEI TE DIZER.')<=0
  |stringdist(dados$texto,'NO MOMENTO NAO ME RECORDO')<=3
  |stringdist(dados$texto,'NAO')<=4
  |stringdist(dados$texto,'RECUSA')<=2
  |stringdist(dados$texto,'NAO NAO.')<=2
  |stringdist(dados$texto,'NAO TEM/')<=2
  |stringdist(dados$texto,'NAO SEI')<=2
  |stringdist(dados$texto,'NAO TENHO')<=2
  |stringdist(dados$texto,'NENHUMA')<=2
  |stringdist(dados$texto,'SEM SEGUSTAO.')<=4
  |stringdist(dados$texto,'NENHUMA SUGESTAO')<=3
  |stringdist(dados$texto,'NADA A DECLARAR')<=3
  |stringdist(dados$texto,'NO MOMENTO NAO.')<=3
  |stringdist(dados$texto,'POR ENQUANTO NAO.')<=3
  |stringdist(dados$texto,'NAO NO MOMENTO NAO')<=4
  |stringdist(dados$texto,'NAO EM O QUE MELHORAR')<=4
  |stringdist(dados$texto,'NAO POR ENQUANTO NAO.')<=4
  |stringdist(dados$texto,'NAO LEMBRO DE NADA NAO')<=4
  |stringdist(dados$texto,'NAO QUERO FAZER SUGESTAO')<=4
  |stringdist(dados$texto,'SEM SUGESTAO - ESTA BOM ASSIM')<=4
  |stringdist(dados$texto,'NAO TUDO TRANQUILO CONTINUANDO ASSIM')<=4
  |stringdist(dados$texto,'NO MOMENTO NAO TENHO NADA NA CABECA.')<=4
  |stringdist(dados$texto,'NAO VEJO NADA POR ENQUANTO')<=4
  |stringdist(dados$texto,'NAO, NESTE MOMENTO NAO.')<=4
  |stringdist(dados$texto,'NAO PORQUE NAO TEM MAIS O QUE MELHORAR.')<=4
  |stringdist(dados$texto,'NAO, NENHUMA.')<=3
  |stringdist(dados$texto,'NAO TENHO A MENOR IDEIA')<=3
  |stringdist(dados$texto,'OLHA NAO PRA MIM TA OTIMO')<=3
  |stringdist(dados$texto,'NAO NUNCA COGITEI')<=3
  |stringdist(dados$texto,'OLHA; A PRINCIPIO NAO')<=3
  |stringdist(dados$texto,'NAO POSSUI SUGESTAO')<=3
  |stringdist(dados$texto,'SEM SUGESTOES')<=3
  |stringdist(dados$texto,'NAO PRA MIM TA OTIMO.')<=3
  |stringdist(dados$texto,'NAO TA PERFEITO')<=3 
  |stringdist(dados$texto,'ESTA OTIMA')<=3 
  
  |stringdist(dados$texto,'NAO SR  RUI')<=2
  |stringdist(dados$texto,'NAO SR JOSE')<=2
  |stringdist(dados$texto,'NAO SR DAVI')<=2
  |stringdist(dados$texto,'NAO SR  LUIS')<=2
  |stringdist(dados$texto,'NAO SR NILZA')<=2
  |stringdist(dados$texto,'NAO SR ANDRE')<=2
  |stringdist(dados$texto,'NAO SR IVANI')<=2
  |stringdist(dados$texto,'NAO SR ANDRE')<=2
  |stringdist(dados$texto,'NAO SR JULIO')<=2
  |stringdist(dados$texto,'NAO SR ELTON')<=2
  |stringdist(dados$texto,'NAO SR  IVAN')<=2
  |stringdist(dados$texto,'NAO SR DIEGO')<=2
  |stringdist(dados$texto,'NAO SR IVONE')<=2
  |stringdist(dados$texto,'NAO SR SONIA')<=2
  |stringdist(dados$texto,'NAO SR MARTA')<=2
  |stringdist(dados$texto,'NAO SR GILDA')<=2
  |stringdist(dados$texto,'NAO SR PAULO')<=2
  |stringdist(dados$texto,'NAO SR MONICA')<=2
  |stringdist(dados$texto,'NAO SR RAQUEL')<=2
  |stringdist(dados$texto,'NAO SR JULLIO')<=2
  |stringdist(dados$texto,'NAO SR MARCIA')<=2
  |stringdist(dados$texto,'NAO SR  ALINE')<=2
  |stringdist(dados$texto,'NAO SR SERGIO')<=2
  |stringdist(dados$texto,'NAO SR  PAULA')<=2
  |stringdist(dados$texto,'NAO SR BIANCA')<=2
  |stringdist(dados$texto,'NAO SR  MARIO')<=2
  |stringdist(dados$texto,'NAO SR THIAGO')<=2
  |stringdist(dados$texto,'NAO SR AMANDA')<=2
  |stringdist(dados$texto,'NAO SR EDIGAR')<=2
  |stringdist(dados$texto,'NAO SR DANIEL')<=2
  |stringdist(dados$texto,'NAO SR  LIANE')<=2
  |stringdist(dados$texto,'NAO SR  LUIZA')<=2
  |stringdist(dados$texto,'NAO SR CLOVIS')<=2
  |stringdist(dados$texto,'NAO SR  JOSUE')<=2
  |stringdist(dados$texto,'NAO SR RAFAEL')<=2
  |stringdist(dados$texto,'NAO SR RYHANA')<=2
  |stringdist(dados$texto,'NAO SR  ZILMA')<=2
  |stringdist(dados$texto,'NAO SR ELIANA')<=2
  |stringdist(dados$texto,'NAO SR SUZANA')<=2
  |stringdist(dados$texto,'NAO SR SOLANGE')<=2
  |stringdist(dados$texto,'NAO SR  SANDRA')<=2
  |stringdist(dados$texto,'NAO SR  HELLIO')<=2
  |stringdist(dados$texto,'NAO SR  CARINE')<=2
  |stringdist(dados$texto,'NAO SR RADAMER')<=2
  |stringdist(dados$texto,'NAO SR SILMARA')<=2
  |stringdist(dados$texto,'NAO SR AQUISON')<=2
  |stringdist(dados$texto,'NAO SR EDILSON')<=2
  |stringdist(dados$texto,'NAO SR ROGERIO')<=2
  |stringdist(dados$texto,'NAO SR CHIRLEY')<=2
  |stringdist(dados$texto,'NAO SR  DENISE')<=2
  |stringdist(dados$texto,'NAO SR MARCELO')<=2
  |stringdist(dados$texto,'NAO SR  ANTONY')<=2
  |stringdist(dados$texto,'NAO SR  LURDES')<=2
  |stringdist(dados$texto,'NAO SR ANDREIA')<=2
  |stringdist(dados$texto,'NAO SR BARBARA')<=2
  |stringdist(dados$texto,'NAO SR  LIZETE')<=2
  |stringdist(dados$texto,'NAO SR  CARLOS')<=2
  |stringdist(dados$texto,'NAO SR EDUARDA')<=2
  |stringdist(dados$texto,'NAO SR  NILTON')<=2
  |stringdist(dados$texto,'NAO SR JANAINA')<=2
  |stringdist(dados$texto,'NAO SR ADILSON')<=2
  |stringdist(dados$texto,'NAO SR MARLENE')<=2
  |stringdist(dados$texto,'NAO SR  SIMONE')<=2
  |stringdist(dados$texto,'NAO SR  MARCIA')<=2
  |stringdist(dados$texto,'NAO SR  ELUIDI')<=2
  |stringdist(dados$texto,'NAO SR OSCELIA')<=2
  |stringdist(dados$texto,'NAO SR  KLEBER')<=2
  |stringdist(dados$texto,'NAO SR  CAMILA')<=2
  |stringdist(dados$texto,'NAO SR  AIRTON')<=2
  |stringdist(dados$texto,'NAO SR CAROLINA')<=2
  |stringdist(dados$texto,'NAO SR  EDUARDO')<=2
  |stringdist(dados$texto,'NAO SR  GERALDO')<=2
  |stringdist(dados$texto,'NAO SR  ADRIANO')<=2
  |stringdist(dados$texto,'NAO SR EDINELMA')<=2
  |stringdist(dados$texto,'NAO SR  RONALDO')<=2
  |stringdist(dados$texto,'NAO SR  ANTONIO')<=2
  |stringdist(dados$texto,'NAO SR  EDILENY')<=2
  |stringdist(dados$texto,'NAO SR-GISLAYNE')<=2
  |stringdist(dados$texto,'NAO SR CRISTINA')<=2
  |stringdist(dados$texto,'NAO SR  MARCELO')<=2
  |stringdist(dados$texto,'NAO SR ORACILIO')<=2
  |stringdist(dados$texto,'NAO SR  FERNANDA')<=2
  |stringdist(dados$texto,'NAO SR  GUILERMY')<=2
  |stringdist(dados$texto,'NAO SR ANTONINHO')<=2
  |stringdist(dados$texto,'NAO SR  CRISTIAO')<=2
  |stringdist(dados$texto,'NAO SR HENRRIQUE')<=2
  |stringdist(dados$texto,'NAO SR  LUCRECIA')<=2
  |stringdist(dados$texto,'NAO SR  CLAUDETI')<=2
  |stringdist(dados$texto,'NAO SR  FRANCISCO')<=2
  |stringdist(dados$texto,'NAO SR  ENEZENITA')<=2
  |stringdist(dados$texto,'NAO SR  ANA LUCIA')<=2
  |stringdist(dados$texto,'NAO SR JOAO JORGE')<=2
  |stringdist(dados$texto,'NAO SR  HERRINQUE')<=2
  |stringdist(dados$texto,'NAO SR MARIA LURDES')<=2
  |stringdist(dados$texto,'NAO SR  LUIS CARLOS')<=2
  |stringdist(dados$texto,'NAO SR  MARIA ANGELA')<=2
  |stringdist(dados$texto,'NAO SR DANIELE FONCECA')<=2
  |stringdist(dados$texto,'NAO SR  MARIA DE LURDES')<=2
  
  |stringdist(dados$texto,'NAO SR MARIA')<=2
  |stringdist(dados$texto,'NAO SR  JOANA')<=2
  |stringdist(dados$texto,'NAO SR NAHARA')<=2
  |stringdist(dados$texto,'NAO SR  MARIA')<=2
  |stringdist(dados$texto,'NAO SR KLEBER')<=2
  |stringdist(dados$texto,'NAO SR  EDSON')<=2
  |stringdist(dados$texto,'NAO SR  LEILA')<=2
  |stringdist(dados$texto,'NAO SR EDISON')<=2
  |stringdist(dados$texto,'NAO SR CAMILA')<=2
  |stringdist(dados$texto,'NAO SR  RAFAEL')<=2
  |stringdist(dados$texto,'NAO SR  ALZIRA')<=2
  |stringdist(dados$texto,'NAO SR LUSINET')<=2
  |stringdist(dados$texto,'NÃO,POR ENQUANTO.')<=4
  
  
  
      #para campos vazios: 
  |is.na(dados$texto)
  
  ,1,0)